name: scripts
description: Scripts that support the creation of Dart's docker images.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  file: ^7.0.1
  http: ^1.3.0
  pub_semver: ^2.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.1
  test: ^1.25.15
