name: scripts
description: Scripts that support the creation of Dart's docker images.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  file: ^7.0.0
  http: ^1.2.2
  pub_semver: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  test: ^1.25.7
