name: scripts
description: Scripts that support the creation of Dart's docker images.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  collection: ^1.15.0
  file: ^6.1.0
  http: ^0.13.3
  http_retry: ^0.2.0
  pub_semver: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.3
